run on window platform
1. "#pragma pack" DOES NOT work on visual studio 2019, need to find why. just rewrite uint24_t with char[3] as a workaround.
2. error C2872: 'byte': ambiguous symbol
3. MUST include winsock2.h before windows.h
4. std::max and std::min issue